name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

env:
  DATABASE_TEST_PORT: 5432
  DATABASE_USERNAME: user
  DATABASE_PASSWORD: pwd
  DATABASE_NAME: database
  NODE_VERSION: 18.x

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Generate SBOM with npm run sbom
        run: npm run sbom

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

  validation:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install project
        run: npm ci

      - name: Run formatter (prettier)
        run: npm run format:check

      - name: Run linter (eslint)
        run: npm run lint:check

      - name: Run tests
        run: npm run test:covall --verbose

      - name: Generate html coverage report
        run: npm run html-coverage

      - name: Generate compodoc documentation
        run: npm run docs:build

      - name: Upload html coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/html

      - name: Upload compodoc documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: documentation
